sudo: required

language: shell
services: [docker]
script:
  #
  # Don't do that as curl is already installed
  # - sudo apt-get upgrade
  # - sudo apt-get update
  # - sudo apt-get install -y --no-install-recommends curl
  #
  # Do tests
  - curl -fsSL https://goss.rocks/install | sudo sh
  - ./test.sh php5.6
  - ./test.sh php7.2
