version: '2'
services:
  xhgui:
    image: edyan/xhgui:php7.2
    # I need to access xhgui
    ports:
      - "9000:80"
  php:
    hostname: php
    command: /usr/bin/php -S 0.0.0.0:80 -t /var/www
    image: edyan/php:7.2 # That image contains mongodb extension from PECL
    # To have xhgui sources mount xhgui's volumes
    volumes_from: [xhgui]
    ports:
      - "8000:80"
    volumes:
      - "./src:/var/www"
